apiVersion: apps/v1
kind: Deployment
metadata:
  name: road-to-secure-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: road-to-secure-kubernetes
  template:
    metadata:
      labels:
        app: road-to-secure-kubernetes
    spec:
      securityContext:
        runAsGroup: 4444
        runAsUser: 1234
        runAsNonRoot: true
      containers:
      - name: road-to-secure-kubernetes
        image: nsmith5/road-to-secure-kubernetes:2
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: REDIS_ADDR
          value: redis:6379
        - name: REDIS_PASSWD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
        ports:
        - containerPort: 8080

